Use an explicit handle when spawning RPC calls
This resolves a panic like the following, which is caused when a
non-Tokio thread tries to broadcast a transaction, for example
when a transaction is broadcasted indirectly by the background
processor.

```
thread '<unnamed>' panicked at 'there is no reactor running, must be called from the context of a Tokio 1.x runtime', src/bitcoind_client.rs:253:9
```